### ISSUE TITLE
Installation instructions outdate and no longer works.

### ISSUE THREAD

**Issue by ZerkerEOD** [optiv/Talon#3]
Due to go switching to `go install` the method doesn't work. If you try `go install` and use the @latest tag you get an error that it is not a main package and doesn't work for the building. Any tips?

**Comment by jdelta1** [comment]
See PR #8. Try `go install -v github.com/optiv/Talon@latest`

**Comment by ZerkerEOD** [comment]
I think I had an error when I was doing go install because it works now but I forgot to come back and report it. Your method does work though for anyone else looking.
